### ISSUE TITLE
PyPI-Assistant extension for VSCode does not read pyproject.toml when using uv as project manager, but works with requirements.txt

### ISSUE THREAD

**Issue by mrchoke** [Twixes/pypi-assistant#31]
When working with a project that uses uv as the project manager, the PyPI-Assistant extension for VSCode does not recognize or read the pyproject.toml file. However, it continues to function properly when the project uses a requirements.txt file for dependency management.

The project structure is as follows:

```
.venv/
app/
.python-version
pyproject.toml
uv.lock
```

The contents of the pyproject.toml are:

```toml
[project]
name = "dev-reserve-api"
version = "0.1.0"
description = "Dev Reserve API"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.13.2",
    "asyncpg>=0.29.0",
    "fastapi-users[sqlalchemy]>=13.0.0",
    "fastapi[all]>=0.115.0",
    "pandas>=2.2.2",
    "sqlalchemy[asyncio]>=2.0.34",
]
```

Expected Behavior:
The PyPI-Assistant extension should detect and properly read the pyproject.toml file for dependency management when uv is used as the project manager.

Actual Behavior:
The extension does not recognize the dependencies listed in pyproject.toml, but it works as expected with requirements.txt if used.

Steps to Reproduce:

1.	Create a project with the above structure, using uv as the project manager.
2.	Define the dependencies in the pyproject.toml file.
3.	Open the project in VSCode with the PyPI-Assistant extension installed.
4.	Notice that the extension does not recognize the dependencies listed in pyproject.toml.

Environment:

•	VSCode version: 1.93.1
•	PyPI-Assistant extension version: 2.1.2
•	Python version: 3.12
•	uv project manager version: 0.4.10
•	OS: Docker Container Debian 12

Let me know if additional information is needed! Thank you for your support.
